### ISSUE TITLE
Breaking issue in 1.0.1

### ISSUE THREAD

**Issue by EmmEm** [havard/node-openid#160]
```
TypeError: binary is not a function
    at Function.from (native)
    at from (native)
    at _base64encode (/x/node_modules/passport-openid/node_modules/openid/openid.js:97:10)
    at _bigIntToBase64 (/x/node_modules/passport-openid/node_modules/openid/openid.js:106:10)
    at Object.openid.associate (/x/node_modules/passport-openid/node_modules/openid/openid.js:608:35)
    at chooseProvider (/x/node_modules/passport-openid/node_modules/openid/openid.js:816:16)
    at /x/node_modules/passport-openid/node_modules/openid/openid.js:830:7
    at /x/node_modules/passport-openid/node_modules/openid/openid.js:580:7
    at /x/node_modules/passport-openid/node_modules/openid/openid.js:446:16
    at Request._callback (/x/node_modules/passport-openid/node_modules/openid/openid.js:209:7)
```

**Comment by havard** [comment]
Which version of Node is this, and which provider are you trying to associate to?

**Comment by EmmEm** [comment]
Node version: 4.3.1
We are using a custom provider

1.0.0 works, but when updating to 1.0.1 we get this error.

**Comment by EmmEm** [comment]
We are using: https://github.com/jaredhanson/passport-openid

We hade to fork to: https://github.com/EmmEm/passport-openid

And set openId version to 1.0.0 instead of 1.x.x to keep using it.

**Comment by havard** [comment]
Fixed in 1.0.2.
